name: Build DEMO

on:
  push:
    branches:
      - main
jobs:
  # Build job
  build:
    name: Build Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build Demo
        run: npm run build:demo
      - name: Save to demo branch 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/demo # The folder the action should deploy.
          clean: true
